language: python

matrix:
  fast_finish: true
  include:
    - language: generic
      env: PY=3
      os: osx
      env: PYVERS="3.5.4 3.6.5 3.7.0"
    - language: generic
      env: PY=3
      os: osx
      env: TEST_CONDA=1

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ] && [ "${TEST_CONDA}" != "1" ]; then
      brew update;
      brew install sdl2;
      brew install sdl2_mixer;
      travis_wait 30 brew install ffmpeg;
    fi;

before_script:
    cd "$TRAVIS_BUILD_DIR";
    export PYTHONPATH=$PYTHONPATH:$(pwd);
    export USE_SDL2_MIXER=1;

script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ] && [ "${TEST_CONDA}" != "1" ]; then
       mkdir ../wheelhouse;

       for pyver in $PYVERS; do
         git reset --hard;
         git clean -d -x -f;
         pyver_short=${pyver:0:3};

         curl -O -L https://www.python.org/ftp/python/$pyver/python-$pyver-macosx10.6.pkg;
         sudo installer -package python-$pyver-macosx10.6.pkg -target /;
         curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py;
         python$pyver_short get-pip.py --user;
         python$pyver_short -m pip install --upgrade --user pip;
         python$pyver_short -m pip install --upgrade --user cython nose wheel;
         python$pyver_short -m pip install --upgrade delocate;

         python$pyver_short setup.py build_ext --inplace;
         python$pyver_short setup.py bdist_wheel;
         python3 -m nose.core ffpyplayer/tests;

         /Library/Frameworks/Python.framework/Versions/$pyver_short/bin/delocate-wheel dist/*.whl;
         /Library/Frameworks/Python.framework/Versions/$pyver_short/bin/delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl;
         cp dist/*.whl ../wheelhouse/;
       done;

       mkdir upload;
       tar -czvf upload/ffpyplayer-osx-wheels-$(date +%s)$PRE_CMD.tar.gz $(find ../wheelhouse/ -type f -name '*.whl');
       ls ../wheelhouse/;
       ls upload;
    fi;
  - if (([ "${TRAVIS_OS_NAME}" == "osx" ] && [ "${TEST_CONDA}" != "1" ]) || [ "${DOCKER_IMAGE}" != "" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      export UPLOAD_WHEELS=1;
    fi;
